### ISSUE TITLE
No firewalld-applet icon on Gnome 3.12

### ISSUE THREAD

**Issue by bigon** [t-woerner/firewalld#11]
Hello,

As explained in this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1082240), the applet doesn't show any icon with gnome-shell >= 3.12

The bug seems to be in the "check_gnome3()" function and the way it detects whether gnome-shell is running.

**Comment by t-woerner** [comment]
There is a new firewall-applet version in the qt-gui branch: https://github.com/t-woerner/firewalld/blob/qt-gui/src/firewall-applet-qt

Please give this a try and report back if this is working for you.

The applet support in Gtk has been deprecated and will most likely be removed soon, therefore the move away from Gtk is needed.

**Comment by t-woerner** [comment]
The new firewall-applet version is fixing this issue in 0.3.14.
