### ISSUE TITLE
Prioritizing direct rules not working as expected

### ISSUE THREAD

**Issue by TAlex81** [t-woerner/firewalld#110]
Hi,

I am using firewalld version 0.3.9-14 version on Centos7. I have default zone set up as internal and have restricted incoming traffic from specific source IPs by using rich rules. For restricting outgoing traffic to allow to only specific destination IPs, I have used direct rules for OUTPUT chain. I have prioritized the OUTPUT rules, giving the blanket drop rule, a priority of 999 , so that it will be the last rule to be executed. But, after reloading firewalld using _firewall-cmd --reload_ and listing the rules using _iptables -S_ or _iptables -L --line-numbers_ , I see that the OUTPUT DROP rule is inserted somewhere in the middle, rather than at the end. So out of the 123 OUTPUT rules , I have , the DROP rule comes to be at the ~52nd position, thus making the rest of the rules under it to be invalid.
What is the solution for this?
Based on the priority, 999 should be the last rule.
I have priorities ranging from 0 -15 ,998,999

Sample of my _firewall-cmd --direct --get-all-rules_:

```
ipv4 filter OUTPUT 2 -m state --state ESTABLISHED,RELATED -j ACCEPT
ipv4 filter OUTPUT 2 -o lo -j ACCEPT
ipv4 filter OUTPUT 15 -p icmp -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
ipv4 filter OUTPUT 6 -p tcp -m tcp -d 1.2.3.4/32 --dport=22 -j ACCEPT
ipv4 filter OUTPUT 9 -p tcp -d 1.2.3.4/32 --dport=80 -j ACCEPT
ipv4 filter OUTPUT 9 -p tcp -d 5.6.7.8/32 --dport=80 -j ACCEPT
ipv4 filter OUTPUT 8 -p tcp -m tcp -d 5.6.7.8/32 --dport=443 -j ACCEPT
ipv4 filter OUTPUT 8 -p tcp -m tcp -d 1.2.3.4/32 --dport=1443 -j ACCEPT
ipv4 filter OUTPUT 8 -p tcp -m tcp -d 1.2.3.4/32 --dport 80  -j ACCEPT
ipv4 filter OUTPUT 998 -j LOG -m limit --limit 12/min --log-level 4 --log-prefix 'Firewalld OUTPUT DROPPED: '
ipv4 filter OUTPUT 999 -j DROP
```

Thanks!

**Comment by t-woerner** [comment]
This has been fixed already. The version 0.4.3.1 is planned to make it into RHEL-7.3 and CentOS-7.3
