### ISSUE TITLE
applet backtrace when switching NM connection

### ISSUE THREAD

**Issue by bigon** [t-woerner/firewalld#114]
Hi,

When switching my network profile in NM, firewall-applet is giving me the following backtrace:

> 'connexion'
> ERROR:dbus.connection:Exception in handler for D-Bus signal:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
>     self._handler(*args, **kwargs)
>   File "/usr/bin/firewall-applet", line 766, in nm_signal_receiver
>     self.update_tooltip()
>   File "/usr/bin/firewall-applet", line 868, in update_tooltip
>     interface=interface))
> KeyError: 'connexion'

I also get a popup telling me that it failed to get the connections from NetworkManager

I'm using debian unstable with NM 1.2.2

Also note that the 1st line of the backtrace above (the "'connexion'") appears every time just when the applet is started

**Comment by t-woerner** [comment]
Which firewalld version is this?

**Comment by bigon** [comment]
Oups forgot to mention it, it's version: 0.4.1.2

**Comment by t-woerner** [comment]
This was a frensh translation issue. Someone translated the whole format string. It is fixed with version 0.4.2.
