### ISSUE TITLE
AttributeError: 'module' object has no attribute 'NM'

### ISSUE THREAD

**Issue by tpgxyz** [t-woerner/firewalld#119]
Hi,
looks like new firewalld-0.4.2 have some issues with missing module:

$ firewall-applet 
Traceback (most recent call last):
  File "/usr/bin/firewall-applet", line 36, in <module>
    from firewall.core.fw_nm import *
AttributeError: 'module' object has no attribute 'NM'

https://issues.openmandriva.org/show_bug.cgi?id=1579

**Comment by hwoarang** [comment]
Hi,

Do you have NetworkManager installed? Sounds like libnm is missing from your system which is something that NetworkManager normally pulls. 

Could you try this patch please?

```
diff --git a/src/firewall/core/fw_nm.py b/src/firewall/core/fw_nm.py
index 3df94c4..6ba1d05 100644
--- a/src/firewall/core/fw_nm.py
+++ b/src/firewall/core/fw_nm.py
@@ -21,7 +21,7 @@
 
 """Functions for NetworkManager interaction"""
 
-__all__ = [ "NM", "check_nm_imported", "nm_is_imported",
+__all__ = [ "check_nm_imported", "nm_is_imported",
             "nm_get_zone_of_connection", "nm_set_zone_of_connection",
             "nm_get_connections", "nm_get_connection_of_interface",
             "nm_get_bus_name" ]
@@ -35,6 +35,7 @@ else:
     try:
         from gi.repository import NM
         _nm_imported = True
+        __all__.append("NM")
     except (ImportError, ValueError):
         NetworkManager = None
         _nm_imported = False
```

**Comment by tpgxyz** [comment]
In my case firewall-applet rpm package requires firewall-applet which requires typelib(NetworkManager)
https://github.com/OpenMandrivaAssociation/firewalld/blob/master/firewalld.spec#L56

I'll try that patch today.

**Comment by hwoarang** [comment]
Thanks. The typelib dependency does not actually pull NetworkManager and as a result libnm is not being installed with it. The previous patch should make firewalld run in case NetworkManager is not installed.

**Comment by tpgxyz** [comment]
Looks like typelib(NM) requires are missing.

**Comment by t-woerner** [comment]
NM is not used outside of the fw_nm module anymore, therefore it can be removed from __all__.

**Comment by t-woerner** [comment]
Nope, firewall-config is using NM.DBUS_* still

**Comment by hwoarang** [comment]
@t-woerner indeed. How does the propose patch look do you? if it's acceptable I can prepare a PR for you

**Comment by t-woerner** [comment]
I think it would be better to add a function like nm_get_interface to fw_nm and drop NM from the __alll__ list then. The new function can then be used in firewall-config and firewall-applet.

**Comment by t-woerner** [comment]
As there is no typelib provide in Fedora, I will add a requires to NetworkManager-libnm

**Comment by hwoarang** [comment]
True, so it needs downstream fixing to require libnm and also upstream fix to clean up the NM module import. I will take care of the upstream one and the downstream SUSE thing since we are affected by the same problem as well. Thank you for your input.

**Comment by t-woerner** [comment]
I have a fix ready..

**Comment by linxuanyi** [comment]
？
