### ISSUE TITLE
breaks IPv6 connectivity on systems without /etc/sysconfig/network-scripts

### ISSUE THREAD

**Issue by mbiebl** [t-woerner/firewalld#121]
Version: 0.4.2
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826961

Dear Maintainer,

with the last update, NetworkManager does not seems able to bring up
IPv6 connectivity when firewalld is enabled. Disabling firewalld service
and reloading network brings back IPv6 connectivity.

It looks like it comes from that error:

firewalld[988]: ERROR: Calling post func <function ifcfg_set_zone_of_interface at 0x7f8b7208d378>(('home', 'enp0s31f6')) failed: [Errno 2] Aucun fichier ou dossier de ce type: '/etc/sysconfig/network-scripts'

which cames from a line[0] in the firewalld package which is not present
in previous versions[1]. The programs tries to access
`/etc/sysconfig/network-scripts` which does not exists in debian (but
exists in Fedora/RH/CentOS).

I'm not sure about what log and other info to provides since the problem
is not very clear…

[0]https://github.com/t-woerner/firewalld/blob/v0.4.2/src/firewall/config/__init__.py.in#L88
[1]https://github.com/t-woerner/firewalld/blob/v0.4.1.2/src/firewall/config/__init__.py.in#L87

**Comment by hwoarang** [comment]
Hi,

I believe this is fixed in commit 1144eeea48fdcf109511588544f5b2b2f04ce2bb. Does that patch work for you?

**Comment by adepasquale** [comment]
Thanks @hwoarang, your patch works great for me. @t-woerner do you plan to release a new version soon?

**Comment by t-woerner** [comment]
@adepasquale I plan to have a new release next week.
