### ISSUE TITLE
Qt5 applet

### ISSUE THREAD

**Issue by tpgxyz** [t-woerner/firewalld#128]
Hi,

when firewall-applet-qt5 will be included into a release ?

**Comment by t-woerner** [comment]
I have made a Qt5 version, but it behaved teribble with KDE5. It was half included and not working at all. It did not seem to have problems with other desktops though. I tried to get it working with one of our KDE guys, but it simply was not possible. It would only have been possible to get it working if the applet would have been written in C. If this is not the case any more, then I am fine with a Qt5 version.

**Comment by tpgxyz** [comment]
I've prepared this patch to use python-qt5
https://github.com/OpenMandrivaAssociation/firewalld/blob/master/firewalld-0.4.3-use-PyQt5-for-applet.patch

I'm currently running it and it seems working. Can you please take a look in it ?

**Comment by kkofler** [comment]
This really needs to be retested. The bug you were running into months ago should be long fixed. And in the unlikely event it's not, we need to get it fixed ASAP. Qt 5 `QSystemTrayIcon` should just work on Plasma 5.

**Comment by tpgxyz** [comment]
Thanks for merging it !
