### ISSUE TITLE
firewalld.service should use network-pre.target

### ISSUE THREAD

**Issue by mbiebl** [t-woerner/firewalld#137]
Hi,

see the dicussion at
https://lists.freedesktop.org/archives/systemd-devel/2016-July/037036.html
and the documentation at
https://www.freedesktop.org/software/systemd/man/systemd.special.html#network-pre.target

firewalld.service should use 
Before=network-pre.target
instead of
Before=network.target

This also means, it should be possible to drop the explicit
After=NetworkManager.service. NetworkManager.service is started as part of network.target, so ordered after network-pre.target.

**Comment by Siosm** [comment]
I've prepared a pull request for this issue: #126.

**Comment by t-woerner** [comment]
Is the network-pre.target available in all systemd versions?

**Comment by mbiebl** [comment]
It's available since v214.

**Comment by Siosm** [comment]
Which means it's available in Debian 8 (https://packages.debian.org/jessie/systemd) and RHEL/CentOS 7 (http://centos-packages.com/7/package/systemd/).

**Comment by marcosfrm** [comment]
https://lists.freedesktop.org/archives/systemd-devel/2016-July/037242.html

basic.target + DefaultDependencies=yes...

**Comment by Siosm** [comment]
I've updated my pull request to use multi-user.target instead of basic.target

**Comment by mbiebl** [comment]
I'd say this is incorrect. Instead of using multi-user.target, firewalld.service should use DefaultDependencies=no and add explicit dependencies on what it needs.
firewalld.service wants to run before network-pre.target, which can be pretty early during boot

**Comment by Siosm** [comment]
Could you elaborate on the reasons this is incorrect? All the iptables related units I could find are using multi-user.target and Before=networt-pre.target will ensure firewalld is started before the network is setup. Moreover, it already depends on dbus and polkit which are not pulled-in by basic.target. Thus those would have to be changed before firewalld. Thus I don't see any reason it absolutely needs to be started before basic.target.

**Comment by Siosm** [comment]
You may close this issue as #126 is merged. Thanks.
