### ISSUE TITLE
Problem with the behavior of default zone.

### ISSUE THREAD

**Issue by cmercier** [t-woerner/firewalld#140]
Hi,

I'm using firewalld on Ubuntu 14.04, version 0.3.7.

I've discovered that even if you assign an interface to a specific zone, it's still included in default zone.

I've assigned my eth0 to public and by default I want to use the trusted zone (private interfaces not opened to the outside world, so it's not filtered). But when I look to my iptables rules, it's not what is applied.

````bash
Chain INPUT_ZONES (1 references)
     pkts bytes target     prot opt in     out     source               destination         
      421 20749 IN_public  all  --  eth0   any     anywhere             anywhere            
      183  6469 ACCEPT     all  --  +      any     anywhere             anywhere
````

As you can see, the default zone is assigned to any interface with the joker "+". So even if a packet is filtered and supposed to be refused in public, it will be always accepted by the default trusted zone which accept everything.

Is there a problem in that behavior ? If not, can you explain me the goal of assigning interfaces to different zones if at the end everything will go in the default zone (trusted here). Why eth0 is not excluded of the default zone ?

Thanks in advance for your answer.

**Comment by t-woerner** [comment]
The zone assignments have been changed and fixed with version 0.3.9.3 to use goto instead of jump in this case. With this the default zone is only used for sources and interfaces that are not bound/assigned to another zone.
