### ISSUE TITLE
Please call syslog.openlog() to work-around Python issue 27875

### ISSUE THREAD

**Issue by canvon** [t-woerner/firewalld#147]
When using syslog.syslog() without calling openlog() before, it gets called automatically with no arguments, which then should set the logging identifier "to sys.argv[0] with leading path components stripped". It does not strip the final slash, though. So firewalld ends up logging, e.g.:

```
# firewall-cmd --permanent --delete-zone=test
Error: INVALID_ZONE: test

Aug 27 18:24:47 blackbox /firewalld: ERROR: INVALID_ZONE: test
```

The additional slash appears as most unusual, and may lead to the impression that there would be a bug in firewalld which causes this (which there isn't), or a chroot would be involved (which appears is not the case). So I consider the additional slash a bug and filed https://bugs.python.org/issue27875

Until that gets fixed (if at all), a work-around by calling syslog.openlog() with an explicit identifier would be nice. (While at it, that could include the PID as well (via logoption=syslog.LOG_PID?) -- when viewing the systemd journal, the PID seems to get inserted automatically anyhow, but in the plain rsyslogd log files, it is missing for firewalld.) The documentation is at https://docs.python.org/3/library/syslog.html

**Comment by t-woerner** [comment]
Fixed in https://github.com/t-woerner/firewalld/commit/adb927065989a305d1a6a412c73218c67f86cf11

**Comment by t-woerner** [comment]
Thanks for the patch, I used it as a base with reference to your patch.

**Comment by canvon** [comment]
Thank you. :)

That renders PR #153 unnecessary.
