### ISSUE TITLE
bug in ipXtables.py due to usage of pop on rule list object removing table from rule

### ISSUE THREAD

**Issue by xlfe** [t-woerner/firewalld#152]
[This commit](https://github.com/t-woerner/firewalld/commit/e34e2ece3da2997748427db3d441b22a7a0ec91b) introduced a bug

In set_rules you have the following code block:

```python
    def set_rules(self, rules, flush=False):
        temp_file = tempFile()

        table_rules = { }
        for rule in rules:
            table = "filter"
            # get table form rule
            for opt in [ "-t", "--table" ]:
                try:
                    i = rule.index(opt)
                except ValueError:
                    pass
                else:
                    if len(rule) >= i+1:
                        rule.pop(i)
                        table = rule.pop(i)
```

Which is called via  fw_transaction -> execute() -> rules() (in fw.py)

```python
    def execute(self, enable):
        log.debug4("%s.execute(%s)" % (type(self), enable))

        rules, modules = self.prepare(enable)

        # pre
        self.pre()

        # stage 1: apply rules
        error = False
        done = [ ]
        for ipv in rules:
            try:
                self.fw.rules(ipv, rules[ipv])
            except Exception as msg:
                error = True
                if not self.generous_mode:
                    log.warning(msg)
            else:
                done.append(ipv)
```

The problem is you're removing the first two items form the rule using pop - which if the self.fw.rules() part fails and generous_mode is enabled, means the table is no longer included in the rule.

This popped up as a problem on my system:

```bash
2016-09-03 17:18:33 WARNING: '/usr/sbin/iptables -w -I PREROUTING_direct 1 -m mac --mac-source BLAH -j MARK --set-mark 1' failed:
etc...
```

The system has iptables 1.4.21 which doesn't seem to like the command:

```bash
[root@router core]# cat test.rule
*nat
-I PREROUTING_direct 1 -m mac --mac-source xx:xx:xx:xx:xx -j MARK --set-mark 1
COMMIT
[root@router core]# iptables-restore < test.rule
iptables-restore: line 2 failed
[root@router core]#
```

Which then triggers firewalld to try individually. But this also fails because of the bug mentioned at the start.

One fix would be (the rules retain the table and are therefore applied correctly)

```python
    def set_rules(self, rules, flush=False):
   ....
        for _rule in rules:
            rule = _rule.copy()
       ...
```
And I'm guessing this also applies to eb as well as ip.

**Comment by t-woerner** [comment]
You are right, this is an issue. I am about to fix this in ipXtables.py and ebtables.py with a solution similar to yours. In ebtables the code is also lacking support for the "--table" option addtionally to "-t".
