### ISSUE TITLE
dot in service file name

### ISSUE THREAD

**Issue by StefanLindner** [t-woerner/firewalld#156]
Using firewalld Version 0.3.9 Release 14.el7 under CentOS 7.2 has aproblem if the "firewalld service configuration file" has a dot in its name.

/etc/firewalld/services/postgresql-9.6.xml leads to the error message "Error: INVALID_SERVICE: postgresql-9.6" when registering it with
firewall-cmd --permanent --zone=public --add-service=postgresql-9.6

Changing the file name to postgresql-96 and registering it with firewall-cmd --permanent --zone=public --add-service=postgresql-96 works.

Is the dot in the filename forbidden? Did not find any hint in the documentation or is this a bug?

**Comment by t-woerner** [comment]
Dots are not allowed in service names. Only alphanumeric with additional dash and underscore are allowed.
This information is missing in the firewalld.service man page.

**Comment by StefanLindner** [comment]
Thank you for your fast reply and this clarifiacation.
