### ISSUE TITLE
how can I save the rule via  firewall-cmd --direct --add-rule ?

### ISSUE THREAD

**Issue by airforce-captain** [t-woerner/firewalld#157]
# rpm -qa|grep firewalld
firewalld-0.3.9-14.el7.noarch

# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.1 (Maipo)

--------------------------------------------------------------

I just want add some custom  rule  at  after firewall reload still work, they can be permanent save in a conf or some files.

have any ideas ?

sorry , forgive me for my bad English..

**Comment by t-woerner** [comment]
Just add the --permanent option to your command to add the rule to the permanent environment.
