### ISSUE TITLE
IPv6_rpfilter=yes causes errors. Can't reload firewalld

### ISSUE THREAD

**Issue by Jakobud** [t-woerner/firewalld#160]
I am on a CentOS 7 VPS (openvz). I haven't had any issues with `firewalld` as far as I can remember. Today I needed to restart the VPS. Afterwords, `firewalld` would not run:

```
# firewall-cmd --state
not running

# firewall-cmd --reload
Error: '/sbin/ip6tables -w -t raw -I PREROUTING 2 -m rpfilter --invert -j DROP' failed: ip6tables: No chain/target/match by that name.
```

Okay... I'm not sure exactly what is going on here. I am far from an IPTABLES expert or firewalld expert... 

If I change `IPv6_rpfilter` to `no` in `/etc/firewalld/firewalld.conf` then I get:

```
# firewall-cmd --reload
Error: ''

# firewall-cmd --state
running
```

So now it works. But that setting... I'm not clear on what it does or how important it is, etc. Is this a bug or is this a sign of something misconfigured?

**Comment by t-woerner** [comment]
Which kernel is in use?
OpenVZ-6 is using an old 2.6.32 kernel with CentOS-7 and RHEL-7. The iptables and ebtables commands on your CentOS-7 installation are not able to use the netfilter version in the old kernel. A rebuild of these packages using the kernel-headers package of the old kernel should get the commands working. If you are already using OpenVZ-7 with a 3.10 kernel, then there is an other issue.

**Comment by Jakobud** [comment]
Thank you for the info. I will investigate. Is it possible to determine the kernel used on the hardware when I only have access to the OpenVZ instance? This is on a hosted VPS server.

**Comment by t-woerner** [comment]
The command  `uname -r ` should return the kernel version.

**Comment by Jakobud** [comment]
Looks like

```
# uname -r
2.6.32-042stab112.15
```

I wonder if the kernel was changed or something when I restarted my VPS instance.
