### ISSUE TITLE
firewall-cmd get or set description error

### ISSUE THREAD

**Issue by oldfellla** [t-woerner/firewalld#161]
When I enter the following command:
`firewall-cmd --permanent --zone=FedoraWorkstation --get-description` 
 
I get the error:
`Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 1783, in <module>
    cmd.print_and_exit(settings.getDescription())
NameError: name 'settings' is not defined`

In the firewall configuration GUI the default description is still there, I didn't change a thing, I just added my own service to customize ssh port and that's it.
After doing that I was just practicing in the shell with get-services, list-services, and so on and I found this behavior on the get-description. 

Also, entering:
 `firewall-cmd --permanent --zone=FedoraServer --set-description="FedoraServer"`
 
gives:
`Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 1778, in <module>
    settings.setDescription(a.set_description)
NameError: name 'settings' is not defined`

My configuration is nearly fresh install, with a single adapter  and for my home PC so really basic.
I hope the problem is not me and the new tool...

**Comment by hwoarang** [comment]
Hi,

What version is this?

I think this is fixed in 0.4.4 with the b67a186b32f832656eefb604b9460f1df5c37a56 commit

**Comment by oldfellla** [comment]
Hello,
Yes, you are right, it is version 0.4.3.3 on Fedora 24, release 1.fc24. It was late last night and I forgot to enter my OS release and firewalld version; something was telling me to watch again over it after a night of rest but I obviously didn't...
Thank you for your work !!
