### ISSUE TITLE
WARNING: INVALID_HELPER: 'nf_conntrack_netbios_ns' not available in kernel

### ISSUE THREAD

**Issue by orbisvicis** [t-woerner/firewalld#169]
Fedora 4.8.6-201.fc24.x86_64

This is not related to #168, on fedora modinfo is located, as expected, at `/usr/sbin/modinfo`.

Introduced between 0.4.3.3-1.fc24.noarch and 0.4.4.1-1.fc24.noarch.

However, I can manually load the `nf_conntrack_netbios_ns` module.

Upstream report: [Bug 1394597 - Can't enable/disable some services since firewalld-0.4.4.1-1.fc24, claims 'nf_conntrack_netbios_ns' isn't in kernel](https://bugzilla.redhat.com/show_bug.cgi?id=1394597)

**Comment by t-woerner** [comment]
This is due to a sleinux-policy issue that should be fixed soon.

**Comment by t-woerner** [comment]
This has been fixed in Fedora 23+
