### ISSUE TITLE
--add-rich-rule doesn't add to the current default zone

### ISSUE THREAD

**Issue by da2x** [t-woerner/firewalld#174]
Steps to reproduce:

    firewall-cmd --permanent --set-default-zone=home
    firewall-cmd --permanent --new-ipset=dogfood --type=hash:ip
    firewall-cmd --permanent --add-rich-rule='rule source ipset=dogfood drop'

The rich rule is added to FedoraWorkstation (the default default-zone). The rich rule should have been added to the default zone (home in this instance), which is the behavior seen with all the other `--add` commands.

**Comment by da2x** [comment]
Neither does `--add-service`. Never mind then.

**Comment by t-woerner** [comment]
Which firewalld version are you using? The use of --set-default-zone together with --permanent should result in an error:

```
~]# firewall-cmd --permanent --set-default-zone=home
usage: see firewall-cmd man page
Can't use stand-alone options with other options.
```

**Comment by t-woerner** [comment]
Closing as not an issue.
