### ISSUE TITLE
get_nf_conntrack_helpers() fails with SELinux

### ISSUE THREAD

**Issue by zlynx** [t-woerner/firewalld#175]
If development is done using Redhat or Fedora systems, please check that the code works with SELinux Enforcing turned on...

def get_nf_conntrack_helpers() tries to read the /lib/modules files but the current selinux policies do not allow it.

**Comment by pbiering** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1394573

**Comment by t-woerner** [comment]
This has been addresses in Fedora-23+ in stable or testing repositories.

**Comment by zlynx** [comment]
Yes, it seems to work in Fedora 25.
