### ISSUE TITLE
MAC filter doesn't work : firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source mac=00:50:56:C0:00:08 port port=9200 protocol=tcp accept'

### ISSUE THREAD

**Issue by vbnetvbnet** [t-woerner/firewalld#178]
Now I want to open port 9200 to only one specific source MAC address. I executed the following command, but it still reject connection.
`firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source mac=00:50:56:C0:00:08 port port=9200 protocol=tcp accept'`
But it works with this command, open to one specific source IP address:
`firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address=192.168.217.1 port port=9200 protocol=tcp accept'`

My OS version: Centos 7.2
Firewalld version: 0.4.2 (using the rpm packages in http://people.redhat.com/twoerner/firewalld/0.4.2-1.el7/)

Is my configuration wrong? Can someone help me?

**Comment by t-woerner** [comment]
There has been an issue in the version 0.4.2 with mac addresses in rich rules. It has been fixed with this commit for firewalld 0.4.3: https://github.com/t-woerner/firewalld/commit/daffd71

**Comment by t-woerner** [comment]
firewalld 0.4.3 is available for CentOS 7.3
