### ISSUE TITLE
No authorisation asked with menu-entry

### ISSUE THREAD

**Issue by TriMoon** [t-woerner/firewalld#179]
I just installed this on Debian 8 (stretch), and when i click the icon from the menu the below happens:
![firewalld menu usage 2016-12-06 16-34-55](https://cloud.githubusercontent.com/assets/1723378/20927657/367ba700-bbcb-11e6-8899-728b842e117b.png)

I'm using Cinnamon desktop, and running as a user, the root account has a separate password.
The application can't initialize because it needs root i guess, but there aint no request to ask for root permissions.
This is using the default .desktop icon installed by the package...
When adding gksudo to the exec field, the app starts but doesn't honor the theme settings. (I used 'use dark theme for applications when possible' or similar described option. )

**Comment by t-woerner** [comment]
It seem that the policykit authentication request is not done. Is there a polkit authentication agent for your system and desktop? It might be something like polkit-cinnamon-authentication-agent-1. But it could also be polkit-gnome-authentication-agent-1that is normally used for cinnamon. Please check also if polkitd is installed and running.

**Comment by TriMoon** [comment]
> Is there a polkit authentication agent for your system and desktop?

Here is the ouput of my query:
```console
~$ dpkg-query -l *policykit* *polkit* *auth*agent*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
ii  gir1.2-polkit-1.0           0.105-17           amd64              GObject introspection data for PolicyKit
ii  libpolkit-agent-1-0:amd64   0.105-17           amd64              PolicyKit Authentication Agent API
ii  libpolkit-backend-1-0:amd64 0.105-17           amd64              PolicyKit backend API
ii  libpolkit-gobject-1-0:amd64 0.105-17           amd64              PolicyKit Authorization API
ii  policykit-1                 0.105-17           amd64              framework for managing administrative policies and privileg
ii  policykit-1-gnome           0.105-5            amd64              XFCE and Unity authentication agent for PolicyKit-1
un  polkit-1-auth-agent         <none>             <none>             (no description available)
```
Seems that [**polkit-1-auth-agent** is provided by **policykit-1-gnome**](https://packages.debian.org/sid/polkit-1-auth-agent)

> Please check also if polkitd is installed and running.

Looks like it is 👍 
```console
~$ ps|grep polkitd
  658     1 ?        root     root      1-00:24:47 /usr/lib/policykit-1/polkitd --no-debug
```

**Comment by TriMoon** [comment]
Today after a few ```apt-get upgrade``` the dialog to ask for root appeared finally.
So the issue as mention seems fixed now.

However, probably due to me dropping the ```nvidia-legacy-340xx``` drivers and reverting to the default, i no longer see the applet in my system tray.
The applet process IS running though, as can be observed using ```ps```...
(I'm sure it will popup-back soon after a few upgrades...)
