### ISSUE TITLE
make[3]: *** No rule to make target 'firewallctl.1', needed by 'all-am'.  Stop.

### ISSUE THREAD

**Issue by tpgxyz** [t-woerner/firewalld#183]
Hi,

i can't build firewalld-04.4.2 because of error:

Making install in man1
make[3]: Entering directory '/builddir/build/BUILD/firewalld-0.4.4.2/doc/man/man1'
make[3]: Leaving directory '/builddir/build/BUILD/firewalld-0.4.4.2/doc/man/man1'
make[3]: *** No rule to make target 'firewallctl.1', needed by 'all-am'.  Stop.
make[2]: *** [Makefile:364: install-recursive] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/firewalld-0.4.4.2/doc/man'
make[1]: *** [Makefile:364: install-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/firewalld-0.4.4.2/doc'
make: *** [Makefile:404: install-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.60556 (%install)

More logs can be found here
https://abf.openmandriva.org/build_lists/88622

**Comment by t-woerner** [comment]
As I am not able to access the log path (404 Not Found), I can only guess that the generation of the ma pages was not successful.

**Comment by tpgxyz** [comment]
@t-woerner Hi, i found the issue. Looks like github sources in release tab are broken.
