### ISSUE TITLE
firewalld-config, can not enter/save an IP address with netmask in Zones

### ISSUE THREAD

**Issue by EinerPetersen** [t-woerner/firewalld#186]
firewalld-0.4.3.2-8.el7.noarch
firewall-config-0.4.3.2-8.el7.noarch

In the "Zones" -> Sources ->Add, "Address" dialog pop-up, with IP selected ------ can not save an {ip_address}/{netmask} value.  "OK" button is disabled/greyed-out, can only Cancel with no entry made to the settings. Does work with entries of the form {ip_address} and no netmask (1.1.1.1 works but 1.1.1.1/32 does not) ... same goes for any address entry including a netmask (pattern [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[/]{0,1}[0-9]{1,2} for example)

Einer

**Comment by t-woerner** [comment]
This has been addressed already for 0.4.4, but seems to not be complete.

**Comment by EinerPetersen** [comment]
Hi Thomas,


OK, thanks :-)


I "Hacked" my way around it for now (with a lot of trail and error of
course :-) I am not very good at Python ....) ..... and it is working
for me at the moment (without breaking anything else ..... I hope :-))


(My very "unelegant" hack :-))
====================================

functions.py

=========

    151
    152 def checkIP(ip):
    153     """ Check IPv4 address.
    154
    155     @param ip address string
    156     @return True if address is valid, else False
    157     """
    158
    159     try:
    160         socket.inet_pton(socket.AF_INET, ip)
    161     except socket.error:
    162 ### EINERIZED - this is broken
    163         return True
    164 #        return False
    165     return True
    166
    167 def checkIP6(ip):
    168     """ Check IPv6 address.
    169
    170     @param ip address string
    171     @return True if address is valid, else False
    172     """
    173
    174     try:
    175         socket.inet_pton(socket.AF_INET6, ip)
    176     except socket.error:
    177 ### EINERIZED - this is broken
    178         return True
    179 #        return False
======================================

Also, I like the IPSETS functionality ..... I am playing with it to see
how well it works vs what I have already done
