### ISSUE TITLE
Constraining output rules

### ISSUE THREAD

**Issue by laurivosandi** [t-woerner/firewalld#197]
Hi, I was positively surprised about firewalld integration with NetworkManger in Ubuntu 16.04. However it seems zone rules only affect inbound packets not the outgoing ones.

A laptop that has been joined to AD domain is rather chatty on the network (ports 53, 88, 389, etc). All those connections should go only to VPN tunnel so for the wireless connection where I select default zone (public I presume) the outgoing connections should be filtered.

Is this planned for future releases or is there an easy way to add the filtering in current releases?

**Comment by teadur** [comment]
https://github.com/t-woerner/firewalld/issues/32
You can add outgoing rules via direct rules

**Comment by t-woerner** [comment]
Output filtering support is proposed for firewalld-0.5.

**Comment by laurivosandi** [comment]
Still - what about some examples how to implement it currently with direct rules?

**Comment by t-woerner** [comment]
@laurivosandi: At the moment it is only possible to add rules to the general output chain, not zone specific output rules.

I have created a new branch for output-filtering: https://github.com/t-woerner/firewalld/tree/output-filtering. There is the patch @etcinit referenced in #32 with an additional one by me to make source bindings in zones are working also and do not lead to a trace back. With these patch it is possible to add zone specific OUTPUT rules.

In #32 there is also an example how to use these new zone specific OUTPUT chains in direct rules.
