### ISSUE TITLE
 firewall applet icon does not appear in Plasma 5 system tray

### ISSUE THREAD

**Issue by t-woerner** [t-woerner/firewalld#23]
KDE5 is not supporting old style Gtk applets any more. Only appindicator enhanced Gtk applets or Qt applets are working.

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1218760

**Comment by t-woerner** [comment]
There are some issues with appindicator:
- Only one menu possible for the applet. No support for context menus with the right click.
- Existing icons are not shown in Xfce for example without any error. If icon names are used that do not exist, then the "missing icon" is shown.

**Comment by phocean** [comment]
+1 It would be nice to have a solution for KDE 5. Thanks.

**Comment by t-woerner** [comment]
There is a new firewall-applet version in the qt-gui branch: https://github.com/t-woerner/firewalld/blob/qt-gui/src/firewall-applet-qt

Please give this a try and report back if this is working for you.

**Comment by rdieter** [comment]
I can confirm that one works as advertised, thanks, though long-term I'd recommend you consider using qt5 python bindings (fedora pkg python-qt5) instead of qt4 (fedora pkg PyQt4).

**Comment by phocean** [comment]
Thanks a lot. It loads, however I get a message like "no connection to the firewall daemon".
Of course, firewalld is active and running (systemctl status firewalld.service).

**Comment by t-woerner** [comment]
@phocean What is the output of "firewall-cmd --state"?

**Comment by phocean** [comment]
Here it is:

% firewall-cmd --state
running

**Comment by phocean** [comment]
Here it is:

% firewall-cmd --state
running

**Comment by gbcox** [comment]
Great, works for me.  Thanks very, very much!  That little applet makes a big difference; 
and you don't really notice until it is missing...
I'd also echo what Rex said about qt5 python bindings.  Since this whole issue
reared its head because of Plasma 5, makes perfect sense.

**Comment by t-woerner** [comment]
@phocean this is strange - firewall-cmd and also firewall-applet* are using FirewallClient to talk to firewalld. Have you started firewall-applet-qt in a special way?

**Comment by t-woerner** [comment]
@rdieter I also have a QT5 version of this applet, but it behaves different in KDE5 and is not working as expected: There are no menues at all.

**Comment by jpopelka** [comment]
Works for me too :+1:

**Comment by gbcox** [comment]
@t-woerner Can you post a link to the Qt5 version?

**Comment by t-woerner** [comment]
@gbcox Here it is: https://github.com/t-woerner/firewalld/blob/qt-gui/src/firewall-applet-qt5

**Comment by t-woerner** [comment]
@gbcox Please open an new issue for the Qt5 applet if needed

**Comment by t-woerner** [comment]
Closing this issue as it has been solved with the Qt4 applet
