### ISSUE TITLE
TypeError: position_function() takes exactly 2 arguments (4 given)

### ISSUE THREAD

**Issue by bigon** [t-woerner/firewalld#24]
Hello,

With gnome-shell 3.16, I'm getting the following error when left/right clicking on the icon in the tray:

    TypeError: position_function() takes exactly 2 arguments (4 given)

**Comment by t-woerner** [comment]
There is a new firewall-applet version in the qt-gui branch: https://github.com/t-woerner/firewalld/blob/qt-gui/src/firewall-applet-qt

Please give this a try and report back if this is working for you.

The applet support in Gtk has been deprecated and will most likely be removed soon, therefore the move away from Gtk is needed.

**Comment by t-woerner** [comment]
Closing this issue with the release of the Qt4 firewall-applet which is solving several issues with the Gtk version and will be used as a replacement.
