### ISSUE TITLE
How to Allow Protocol 47?

### ISSUE THREAD

**Issue by bismall** [t-woerner/firewalld#30]
iptables
iptables -A INPUT -p tcp --dport 1723 -j ACCEPT
iptables -A INPUT -p 47 -j ACCEPT

firewalld
firewall-cmd --permanent --zone=public --add-port=1723/tcp
Protocol 47 NOT port 47

I hope to increase PPTP VPN firewall rules on /config/services/
http://poptop.sourceforge.net/dox/gre-protocol-unavailable.phtml

Kind regards,
我又得跑路了

**Comment by t-woerner** [comment]
Please have a look at the new protocols branch: https://github.com/t-woerner/firewalld/commit/1a1a000e7e3c681d309462e679753f5fef888e84

**Comment by t-woerner** [comment]
Right now this is possible with a rich rule only:
firewall-cmd [--permanent] [--zone=X] --add-rich-rule='rule protocol value="47" accept'

With the commit above this is also possible without a rich rule. This will be part of the next firewalld release.
