### ISSUE TITLE
Unspecific NameOwnerChanged DBus matches

### ISSUE THREAD

**Issue by zonque** [t-woerner/firewalld#43]
firewalld seems to install matches for `NameOwnerChanged` signals without being specific about what to track. Such signals are sent every time a client connects to the bus, so the daemon is woken up on each occasion. That doesn't scale and should be fixed, so only peers the daemon is really interested in are tracked.

**Comment by t-woerner** [comment]
The only signal receiver for NameOwnerChanged is in client.py and this one is using org.fedoraproject.FirewallD1 as an argument. It is only covering firewalld NameOwnerChanged signals.

Where do you see this issue?

**Comment by zonque** [comment]
Right, that's odd. We've got reports that a stress test that causes lots of bus IDs to appear and disappear on the bus makes quite some default services on Fedora burn CPU cycles. But you're right, from looking at the code, I don't see how this can happen either. I'll investigate and report again. Thanks!

**Comment by t-woerner** [comment]
python-slip, which is used by firewalld, seems to use unspecific NameOwnerChanged signal receivers, in dbus/polkit.py and dbus/service.py.

**Comment by zonque** [comment]
Yeah, right. I patched python-slip now. FTR: https://fedorahosted.org/python-slip/ticket/2

**Comment by zonque** [comment]
Thanks for looking, anyway :)
