### ISSUE TITLE
Logs to syslog/journald with timestamp in formatted message

### ISSUE THREAD

**Issue by twaugh** [t-woerner/firewalld#47]
When logging to syslog/journald, there is no need to include the timestamp in the formatted message. In fact, doing so makes it harder to filter/match log messages, as the timestamp is always different.

Firewalld should only include the timestamp in formatted log output when logging to stdout or to a file.

**Comment by t-woerner** [comment]
Fixed in https://github.com/t-woerner/firewalld/commit/5141bcc4aea858917121c017cea85ffdf2c9a349
