### ISSUE TITLE
confusing problems with fedora 22 as an openVZ container

### ISSUE THREAD

**Issue by propertunist** [t-woerner/firewalld#50]
greetings!
i am configuring a new fedora 22 server install here that is running from an OpenVZ container and having a lot of trouble with the firewall. at least i think the firewall is the cause.
essentially, i log in remotely via putty and install XFCE so that i can then login to use remote desktop access via x2go. as soon as i install XFCE (or other desktops, such as KDE) i find that after rebooting i cannot login via SSH. at this point i have not found a way to make a change that allows me to log back in via SSH at all - so i have no choice but to reinstall the container and start again.

through exploration i found that the container does not come with firewallD installed and instead has IPTABLES running by default. when XFCE is installed, so too is firewallD. i have confirmed that firewallD is the issue by only installing firewallD and not installing a desktop (after a fresh installation of F22).

so i decided to explore firewallD a bit. in my previous installation (F20) i run firewallD and edit it via the gui - however, my attempts to configure firewallD via the gui in F22 made no difference to the problem of me not being able to login after reboot. i did ensure that the default SSH port was open for the public zone - yet it made no difference.
i have found that when i configure firewallD from the command line, the 'interfaces' parameter that is visible when i run:
```
firewall-cmd --list-all
```
begins populated but after i make any change at all, it then becomes empty - for no apparent reason and i am unable to run any commands successfully to repopulate the parameter. for example, now, when i run:
```
firewall-cmd --zone=public --change-interface=myinterfaceid
```
i see an error message that refers to IPTABLES.. yet iptables is disabled and as far as i am aware there is no requirement for firewallD to use IPTABLES.

what am i missing here? this really shouldn't be this challenging!

i have raised this with the server operators and they have updated the F22 container to the latest version, but that made no difference.

**Comment by propertunist** [comment]
i have now found that firewallD did not associate the virtual ethernet interface on my server with it's public zone (or any other zone). i have ammended that by changing a configuration file, but even after doing that i still face the same behavior and cannot login remotely. when i explore the firewalld service's status messages, i see references to errors relating to ebtables, but i have been informed that this is not the cause of my problems and that i need to instead focus on firewallD. so far i have found no other issues with the firewallD configuration.

**Comment by t-woerner** [comment]
Which error message have you got from iptables?

**Comment by propertunist** [comment]
i just ran that command again and i now see 'success' is returned, without an error message; though this could be related to me already having associated the interface with firewallD by editing:
```
/etc/sysconfig/network-scripts/ifcfg-venet0
```
as i recall though, the success message did not actually translate to true success and i needed to manually edit the file i highlighted here to get the desired effect (and then reload firewall-d or reboot).

i'd really appreciate some help here as i have been stuck with upgrading my server OS for weeks due to this.

**Comment by propertunist** [comment]
i have been informed that this issue is likely related to the fact that i am using a host that is using openVZ and. as a result, the kernel version is forced to be older than the correct one for fedora 22.

**Comment by t-woerner** [comment]
I have seen the issues with OpenVZ some time ago also. Depending on the distribution that is used iptables is not compatible to the netfilter interface in the kernel. This starts with only basic things are usable that are not using any extensions and leads to some extensions are not usable. In the best and rare case iptables is fully working, but this only applies to old distributions.
Sadly there is not really something that can be done in firewalld to fix this. Even the tcp and udp modules might not be usable and therefore there is no filtering possible. iptables simply needs to be rebuild against the kernel that is used to fix this.

**Comment by propertunist** [comment]
i did find the solution for this in the end. i moved to fedora 23, but that didn't solve it.
i found a video online of someone demonstrating line by line how to disable network manager in an appropriate way and once that was done everything worked correctly. i think this is the one: http://openvz.livejournal.com/50063.html?mode=reply

**Comment by t-woerner** [comment]
I do not understand how disabling NM could help with this.

**Comment by t-woerner** [comment]
Aside from that there has been code added to firewalld and also firewall-cmd to make ZONE assignments consistent with NM and the network service.

**Comment by propertunist** [comment]
i don't know the details of why this worked, i just know that it did and nothing else did after months of exploration!
