### ISSUE TITLE
RFE: Option for -j LOG before -j REJECT in INPUT chain

### ISSUE THREAD

**Issue by agajania** [t-woerner/firewalld#59]
In my case, firewalld generates an INPUT chain that looks like:

[root@magnesite ~]# iptables -S INPUT
-P INPUT ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -j INPUT_direct
-A INPUT -j INPUT_ZONES_SOURCE
-A INPUT -j INPUT_ZONES
-A INPUT -p icmp -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited

How about a new configuration option to firewall-cmd like the following?

firewall-cmd --log-rejects-on

This configuration option would insert a new LOG rule to the INPUT chain right before the REJECT rule.  The new rule might look something like:

-A INPUT -j LOG --log-prefix "iptables reject: "

**Comment by hwoarang** [comment]
I too believe that it could be useful to have an option to enable/disable logging for rejects.

**Comment by t-woerner** [comment]
The field LogDenied has been added to firewalld.conf. firewall-cmd provides the --get-log-denied and --set-log-denied=<value> option. The value can be one of all, unicast, broadcast, multicast or off. firewall-config also support it.
