### ISSUE TITLE
Adding and modifying new services with firewall-cmd.

### ISSUE THREAD

**Issue by whatevsz** [t-woerner/firewalld#62]
Right now, `firewall-cmd` can only add a new blank service with `--new-service`, but (as far as I can see) it cannot modify services and add/remove ports from it.

Is there a way to accomplish this, short of writing a new XML file to `/etc/firewalld/services/`(which is also what the python library does)?

Is this a useful feature? If so, I might go ahead and try to implement it.

**Comment by t-woerner** [comment]
Please have a look at the commits. They are adding support to alter services and icmptypes to firewall-cmd and also firewall-offline-cmd. This will be part of the 0.4.0 version that will be released soon.

**Comment by whatevsz** [comment]
Wow this is awesome, thank you very much!
