### ISSUE TITLE
Zones not correctly working

### ISSUE THREAD

**Issue by sedrubal** [t-woerner/firewalld#63]
I think the zone configuration does not really work:

I have two interfaces (Ethernet and WLAN) and the ethernet interface is in `public` zone and the wireless interface is in `home`. In `public` there are no ports open, but in `home` I opened `1714-1764/tcp` and `1714-1764/udp` (for KDE Connect). But it seems that no ports are open until I move both interfaces in `home`.

**Comment by t-woerner** [comment]
Over which interface are you connecting to the machine and from where?

**Comment by sedrubal** [comment]
Ah sorry. I'm connecting from my smart phone over WIFI to my pc.

**Comment by sedrubal** [comment]
Mh maybe I've fooled. Now it is working... Sorry ;)

**Comment by sedrubal** [comment]
no now it doesn't work again...

in `firewall-config` everything looks correct, but `firewall-cmd` says something different, I think:

```sh
$ sudo firewall-cmd --list-all
public (default, active)
  interfaces: enp14s0
  sources: 
  services: dhcpv6-client mdns ssh
  ports: 
  masquerade: no
  forward-ports: 
  icmp-blocks: 
  rich rules: 

$ sudo firewall-cmd --list-all-zones
[...]
home (active)
  interfaces: wlp13s0
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 1714-1764/tcp 1714-1764/udp
  masquerade: no
  forward-ports: 
  icmp-blocks: 
  rich rules: 

[...]
public (default, active)
  interfaces: enp14s0
  sources: 
  services: dhcpv6-client mdns ssh
  ports: 
  masquerade: no
  forward-ports: 
  icmp-blocks: 
  rich rules: 
[...]

$ sudo firewall-cmd --list-ports
$
```

**Comment by sedrubal** [comment]
Mh sorry it was a connection problem...
