### ISSUE TITLE
only 1 command works under funtoo firewalld-0.3.13

### ISSUE THREAD

**Issue by 666threesixes666** [t-woerner/firewalld#7]
--disable-systemd  <--- is this a hard dep?

its setting allow all on all on all first entries, the entire package is pretty much useless, except for the block all network traffic works fine from firewall-applet.

i've tried shields up down multiple zones reloading the fire wall in every which way possible.  i got some icmp blocks from arbitrary iptables rule flushings.  you can find ebuilds in my tripsix overlay on github :-)

**Comment by t-woerner** [comment]
I am sorry, but I do not understand the connection of the "--disable-systemd" option to the other parts in your comment. There is only a "--disable-systemd" option in the configure script to disable creation and installation of the systemd service file in favour of the creation and installation the old init script.

Please explain, what you want to achieve.

**Comment by 666threesixes666** [comment]
system-config-firewall is missing on my system sorry i picked up this ebuild second hand and started to funtooize it.  its just seriously broken with out that command, and the "system" was making me think systemd.  my fault sorry... =(  thanks for the prompt response, maybe you'd like to link https://fedorahosted.org/released/system-config-firewall/
& the link i am yet to find of system-config-firewall-tui to the deps since they're so new?
