### ISSUE TITLE
direct rule gives confusing subnet mask error

### ISSUE THREAD

**Issue by hwoarang** [t-woerner/firewalld#72]
Hi,

I am using 0.3.14.2 and I noticed that the following command leads to a very strange problem

```
~$ firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 1 "-s 192.168.100.0/24 -o tun+ -p tcp -m tcp --dport 33:44 -j MASQUERADE"
Error: COMMAND_FAILED: '/usr/sbin/iptables -w -t nat -I POSTROUTING_direct 1 -s 192.168.100.0/24 -o tun+ -p tcp -m tcp --dport 33:44 -j MASQUERADE' failed: iptables v1.4.21: invalid mask `24 -o tun+ -p tcp -m tcp --dport 33:44 -j MASQUERADE' specified
Try `iptables -h' or 'iptables --help' for more information.
~$
~$ /usr/sbin/iptables -w -t nat -I POSTROUTING_direct 1 -s 192.168.100.0/24 -o tun+ -p tcp -m tcp --dport 33:44 -j MASQUERADE
~$
```
Running the same commands outside of firewalld does the correct thing though.

I also tried the current master(d7d68f8f79a00f1d9ad66acd0fd1d1c10f130ed7) with the --debug option and the same problem exists

```
2016-01-25 20:26:45 DEBUG1: direct.addRule('ipv4', 'nat', 'POSTROUTING', 1, '-s 192.168.100.0/24 -o tun+ -p tcp -m tcp --dport 33:44 -j MASQUERADE')
2016-01-25 20:26:45 ERROR: COMMAND_FAILED: '/usr/sbin/iptables -w -t nat -I POSTROUTING_direct 1 -s 192.168.100.0/24 -o tun+ -p tcp -m tcp --dport 33:44 -j MASQUERADE' failed: iptables v1.4.21: invalid mask `24 -o tun+ -p tcp -m tcp --dport 33:44 -j MASQUERADE' specified
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by hwoarang** [comment]
It does seem that the problem is with whitespace in args items in execve. https://github.com/t-woerner/firewalld/pull/73 fixes the problem for me

**Comment by t-woerner** [comment]
Arguments containing quotes or double quotes may not be split up into separate words. Please think about comments and log labels which could contain spaces and need to be quoted in this case.

**Comment by hwoarang** [comment]
OK true. But why did you close this issue? The bug is still there. Do you have another solution in mind?

**Comment by t-woerner** [comment]
Just remove the quotes form your command to make it work:

```firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 1 -s 192.168.100.0/24 -o tun+ -p tcp -m tcp --dport 33:44 -j MASQUERADE```

**Comment by t-woerner** [comment]
If you are using quotes you mark this as a string that should not be split up.

**Comment by hwoarang** [comment]
I see. Thank you!
