### ISSUE TITLE
Please use PATH instead of harcoding other executables paths

### ISSUE THREAD

**Issue by bigon** [t-woerner/firewalld#79]
Hi,

Apparently with firewalld 0.4, the paths to iptables,ip6tables,... are hardcoded and firewalld is not relying on the path to discover them.

Any reasons for this?

**Comment by t-woerner** [comment]
The paths have been hard coded before also in firewal/core/ebtables.py and firewall/core/ipXtables.py. Now all these can be set using configure at compile time and are central place in firewall/config.

**Comment by t-woerner** [comment]
Closing due to added configure support for the {ip,ip6,eb]tables and ipset commands
