### ISSUE TITLE
system-config-firewall is python 2 only

### ISSUE THREAD

**Issue by 666threesixes666** [t-woerner/firewalld#8]
system-config-firewall only supports python 2.  (thanks in advance)  i tried to run modernize but didnt really get anywhere with that.  i get the following errors when running make install

https://gist.github.com/666threesixes666/0d5f6d9434212b4fc1c6

**Comment by t-woerner** [comment]
system-config-firewall is not part of firewalld and also not working with firewalld. Please use firewall-config.

**Comment by 666threesixes666** [comment]
https://fedoraproject.org/wiki/Features/firewalld-default#Dependencies

**Comment by t-woerner** [comment]
This issue tracker is for firewalld.

There is not even a dependency to system-config-firewall from firewalld. The feature "firewalld-default" for Fedora 18, that you are referencing, was depending on firewalld and also on the old firewall solution with system-config-firewall/lockit.

Please open a bug for system-config-firewall in the Fedora bugzilla.
