### ISSUE TITLE
traceback creating a temp file

### ISSUE THREAD

**Issue by clumens** [t-woerner/firewalld#86]
When running the firewall-offline-cmd that's in rawhide, I'm seeing the following error in just one of our anaconda tests.  It's possible the problem is we're setting up the environment incorrectly, but it might also be a bug on your end.  What do you think?

07:31:08,489 INFO program: Running... /usr/bin/firewall-offline-cmd --enabled --service=ssh
07:31:08,748 INFO program: ERROR: Failed to create temporary file: [Errno 2] No such file or directory: '/run/firewalld/temp.dydn2f42'
07:31:08,749 INFO program: Traceback (most recent call last):
07:31:08,749 INFO program: File "/usr/bin/firewall-offline-cmd", line 33, in <module>
07:31:08,749 INFO program: from firewall.core.fw_test import Firewall_test
07:31:08,749 INFO program: File "/usr/lib/python3.5/site-packages/firewall/core/fw_test.py", line 29, in <module>
07:31:08,750 INFO program: from firewall.core.fw_direct import FirewallDirect
07:31:08,750 INFO program: File "/usr/lib/python3.5/site-packages/firewall/core/fw_direct.py", line 27, in <module>
07:31:08,750 INFO program: from firewall.core import ebtables
07:31:08,751 INFO program: File "/usr/lib/python3.5/site-packages/firewall/core/ebtables.py", line 215, in <module>
07:31:08,751 INFO program: ebtables_available_tables = ebtables().available_tables()
07:31:08,751 INFO program: File "/usr/lib/python3.5/site-packages/firewall/core/ebtables.py", line 56, in __init__
07:31:08,751 INFO program: self.restore_noflush_option = self._detect_restore_noflush_option()
07:31:08,751 INFO program: File "/usr/lib/python3.5/site-packages/firewall/core/ebtables.py", line 77, in _detect_restore_noflush_option
07:31:08,752 INFO program: self.set_rules(rules, flush=False)
07:31:08,752 INFO program: File "/usr/lib/python3.5/site-packages/firewall/core/ebtables.py", line 94, in set_rules
07:31:08,752 INFO program: temp_file = tempFile()
07:31:08,752 INFO program: File "/usr/lib/python3.5/site-packages/firewall/functions.py", line 269, in tempFile
07:31:08,753 INFO program: dir=FIREWALLD_TEMPDIR, delete=False)
07:31:08,753 INFO program: File "/usr/lib64/python3.5/tempfile.py", line 549, in NamedTemporaryFile
07:31:08,753 INFO program: (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
07:31:08,753 INFO program: File "/usr/lib64/python3.5/tempfile.py", line 260, in _mkstemp_inner
07:31:08,753 INFO program: fd = _os.open(file, flags, 0o600)
07:31:08,754 INFO program: FileNotFoundError: [Errno 2] No such file or directory: '/run/firewalld/temp.dydn2f42'
07:31:08,754 DEBUG program: Return code: 1

**Comment by jpopelka** [comment]
Hi, I think it's already fixed (rawhide) https://bugzilla.redhat.com/show_bug.cgi?id=1305175

**Comment by clumens** [comment]
Oh, great, thanks!  Sorry about the duplicate report.
