### ISSUE TITLE
Documentation shortfall?

### ISSUE THREAD

**Issue by bill-hudacek** [t-woerner/firewalld#92]
I'm not sure where to optimally pursue this issue.
I've seen it discussed on many web forums, mailing lists, and only through a "bolt of lightning" lucky click did I find the solution myself.

Now I'd like to somehow contribute by ensuring this specific technical fact is documented at least in the man pages for firewalld.

Here's the technical issue: if you try to use port forwarding, it may not work.  There is no logging, no error messages, no diagnostics of any kind.  It's impossible to 'debug' because of these (separate issues).

But the root cause of the failure is that, given host X at IP 10.0.0.1 and host Y at IP 10.0.0.25, if you set up port 10.0.0.1:25 to forward to port 10.0.0.25:625, the connection will only succeed if host Y has its default route set to host X.

Whatever the reason, I'm not going to dispute the validity of this behavior. However, the fact that firewalld has consistently been lacking in kernel logging (I'm a decades-old Shorewall user!), and also does not report this failure (if indeed it is so) is completely unacceptable to me.  I lost many hours to this issue.

I fear that all over the world, if you add up the time lost by everyone who encounters it, this one single technical issue is 'critical' in its impact.  

I think the least that can be done is to add some explanation or rationale around this behavior to man pages.

Thanks for reading this far. I hope this can be addressed....

**Comment by t-woerner** [comment]
Port forwarding to another machine should work with any hosts in the network. But you have to enable masquerading for this also on the machine, where you added the forwarding rule. firewall-config is asking to enable masquerading if port forwarding is added that is not local.

**Comment by bill-hudacek** [comment]
I'm sorry, but it does not work.  My experience was exactly the same as reported on serverfault (trying a link here..... http://serverfault.com/questions/539766/firewalld-trouble-forwarding-port-25-while-other-ports-forward-just-fine-rich ).  This may not be a firewalld 'intended behavior' but the moment I ensured the default route was set, my problem also went away. Thanks for replying!

**Comment by t-woerner** [comment]
The logging support of rich language forward port rules has been missing. I just fixed this: https://github.com/t-woerner/firewalld/commit/0b62f95249f944513feee8c5b61cdca8b5893de4

**Comment by bill-hudacek** [comment]
Update: I learned something today.  RHEL 6 and 7 are stricter with packet processing - I'd just never come across this before when working with VM guests...

It's possible to relax the restriction on the default route - from https://access.redhat.com/solutions/53031 :

/usr/share/doc/kernel-doc-2.6.32/Documentation/networking/ip-sysctl.txt

rp_filter - INTEGER
        0 - No source validation.
        1 - Strict mode as defined in RFC3704 Strict Reverse Path 
            Each incoming packet is tested against the FIB and if the interface
            is not the best reverse path the packet check will fail.
            By default failed packets are discarded.
        2 - Loose mode as defined in RFC3704 Loose Reverse Path 
            Each incoming packet's source address is also tested against the FIB
            and if the source address is not reachable via any interface
            the packet check will fail.

        Current recommended practice in RFC3704 is to enable strict mode 
        to prevent IP spoofing from DDos attacks. If using asymmetric routing
        or other complicated routing, then loose mode is recommended.

        The max value from conf/{all,interface}/rp_filter is used 
        when doing source validation on the {interface}.

        Default value is 0. Note that some distributions enable it
        in startup scripts.

I made the change in /etc/sysctl.conf: 
**net.ipv4.conf.vmnet8.rp_filter = 0**

(change vmnet8 to the name of your interface).

Hope this helps someone!

**Comment by bill-hudacek** [comment]
One last thought: I would not use '0' on anything but  a virtual NIC.  Esp not on an internet-facing system.  Use '2' if you must.

**Comment by t-woerner** [comment]
With the changed rp_filter setting this is fixed for you, right?

**Comment by bill-hudacek** [comment]
Yes, this was the correct solution that fixed my routing issues.  I'd still like to see logging in firewalld (though I'm on f20 and really, really should upgrade 'soon'!).
